### ISSUE TITLE
deerma-humidifier-jsq5 support

### ISSUE THREAD

**Issue by artusha2** [russtone/homebridge-mi-humidifier#101]
Could you please upgrade to support new release of ZNJSQ01DEM ( EU/RU version) with deerma-humidifier-jsq5 device name ?

Thanks in advance

**Comment by russtone** [comment]
Hey @artusha2,

I've added support for `deerma.humidifier.jsq5` in the latest release 2.4.3. Please check

**Comment by artusha2** [comment]
Excellent, thank you
