### ISSUE TITLE
Not Supported in Homebridge (SmartMi Evaporative Humidifier)

### ISSUE THREAD

**Issue by DmitriiMi** [russtone/homebridge-mi-humidifier#11]
what am I doing wrong?

```
Homebridge: 0.4.45
Miio: 0.15.6
Linux version: 4.14.79-v7+ (gcc version 4.9.3) (Raspberry Pi 2)
Node: 8.2.1
```

<img width="354" alt="2019-01-12 4 32 31" src="https://user-images.githubusercontent.com/14926347/51067461-94586c00-1623-11e9-84c4-62b3ecdb73fb.png">
<img width="800" alt="2019-01-12 4 32 43" src="https://user-images.githubusercontent.com/14926347/51067462-94586c00-1623-11e9-8321-a15eeecc57b2.png">

**Comment by leoneleone** [comment]
I think the problem is the app you’re using doesn’t support Humidifier accessories. 
Have you tried the  Home app?

**Comment by DmitriiMi** [comment]
Yes, but the  Home app writes "accessories not responding".
If remove "Humidifier", that the  house works again.

I added a “humidifier” to HomeKit via [Home Assistant](https://www.home-assistant.io/), but as a fan.
<img width="368" alt="2019-01-13 3 47 39" src="https://user-images.githubusercontent.com/14926347/51080068-072a1b80-16e6-11e9-85f7-5c4403f53f95.png">

**Comment by russtone** [comment]
It seems that you have same problem as mentioned here https://github.com/aholstenson/miio/issues/192, because miio doesn't support zhimi.humidifier.ca1 yet. As a workaround you can try this: https://github.com/russtone/homebridge-mi-humidifier/issues/5#issuecomment-453771970
