### ISSUE TITLE
Will it work with mi humidifier v.2?

### ISSUE THREAD

**Issue by Aekung** [russtone/homebridge-mi-humidifier#16]
Hi,

I would like to ask if the plugin would work with xiaomi mi humidifier v.2 or only v.1 since there’s only v.1 model in your plugin setting according to the manual.

If possible, can u please post the picture of the one that work? xiaomi has so many humidifiers that I’m a but worrying I would end up buying the wrong one.

Thank you very much in advance.

**Comment by russtone** [comment]
Hi,

It is known that it works with SmartMi Germocidal UV Humidifier (`zhimi.humidifier.v1`):
<img src="https://imgaz.staticbg.com/thumb/large/oaupload/banggood/images/2D/19/9d366109-10ff-48cc-bcd5-5b119b264895.jpg" width=300 height=300 />

and using some hacks (see this [comment](https://github.com/russtone/homebridge-mi-humidifier/issues/5#issuecomment-453771970)) with SmartMi Evaporative Humidifier (`zhimi.humidifier.ca1`):

<img src="https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/2/b/2bf19ae3080b5c5f9ef922448d972e404d9d1ef1.jpeg" width=200 />

**Comment by Aekung** [comment]
Dear Russtone,

Thank you for the reply.

Sadly I have already bought one of the Xiaomi Humidifier and its miio model is deerma.humidifier.mjjsq which doesn't work with the plugin (or any as far as I tried).

Wonder if you could have a plan on updating the plugin to work with this model?  Up on googled, I found this information that might be useful somehow but since I know nothing about coding so I can't be sure of. It's mentioned by @rezmus 

`it's new mi humidifier, miio model deerma.humidifier.mjjsq

https://www.xiaomiyoupin.com/detail?gid=109486
https://ibb.co/n1dwCgS

while i don't have device (yet?) i took a look at the plugin so i leave info here if anybody wants to add support. below you can find all props/methods supported by firmware.

{"method":"get_prop","params":["Humidifier_Gear","Humidity_Value","HumiSet_Value","Led_State","OnOff_State","TemperatureValue","TipSound_State","waterstatus","watertankstatus"]}

props

Humidifier_Gear - speed (1-4, 1 Low, 2 Medium, 3 High, 4 Humidity)
Humidity_Value - humidity value (0-100)
HumiSet_Value - desired humidity value? (not used by plugin atm)
Led_State - led state (0 - off, 1 - on)
OnOff_State - power state (0 - off, 1 - on)
TemperatureValue - temperature value
TipSound_State - sound state (0 - off, 1 - on)
waterstatus - water status (0 - insufficient, 1 - normal)
watertankstatus - water tank status (0 - detached, 1 - installed)

methods

{"method":"Set_HumidifierGears","params":[1-4]} - set speed (Humidifier_Gear prop)
{"method":"Set_OnOff","params":[0/1]} - set power off/on (OnOff_State prop)
{"method":"SetLedState","params":[0/1]} - set led off/on (Led_State prop)
{"method":"SetTipSound_Status","params":[0/1]} - set sound off/on (TipSound_State prop)
{"method":"Set_HumiValue","params":[0-100]} - set desired humidity value? (not used by plugin atm)`

I don't know if it can be useful to you if you are planning to upgrade the plugin to work with this new model. I am willing to help you test and try if you can guide me of what you need in order to do so.

Thank you and looking forward to seeing your reply.

**Comment by Aekung** [comment]
Thank you very much for the reply.

I will try asking this in another thread which is about the miio library.

Again, thank you very much.

**Comment by rezmus** [comment]
@Aekung can you share this humidifier to me? i will like to check some things so i can add extended automation support.

**Comment by earlywaff** [comment]
It still doesn't work?

**Comment by Aekung** [comment]
> It still doesn't work?

It still doesn't work. I hope it is implemented later.

**Comment by ArielZgo** [comment]
Hi all, any news on that?

**Comment by russtone** [comment]
Hi @ArielZgo, I've already implemented miio replacement for this project https://github.com/russtone/miio-api and I'm currently woking on plugin update

**Comment by Aekung** [comment]
> Hi @ArielZgo, I've already implemented miio replacement for this project https://github.com/russtone/miio-api and I'm currently woking on plugin update

Woahhhhhhhh!!! Really looking forward to the plugin.

Thanks with loads of lovesssss

**Comment by DJay-X** [comment]
I just ordered the New SMARTMI Silent Smart Air Humidifier 2 (With Display) and hope it will work with our plugin @russtone 
Thanks for the time you are investing, your work and sharing with the community. 👍 

![New-SMARTMI-Silent-Smart-Air-Humidifier-2-For-Home-Air-Damper-Aroma-Diffuser-Essential-Oil-Mist](https://user-images.githubusercontent.com/3874239/79044970-c54d9500-7c08-11ea-93cc-6ec3aee5ae4c.jpg)

**Comment by rezmus** [comment]
it won't work, because zhimi.humidifier.ca4 (with display) is miotspec device.

**Comment by DJay-X** [comment]
But is there a plugin that works with zhimi.humidifier.ca4 and miotspec?
Or could @russtone extend this plugin to also work the protocol? 
Sorry my newbie questions. :) Thx.

**Comment by ArielZgo** [comment]
> Hi @ArielZgo, I've already implemented miio replacement for this project https://github.com/russtone/miio-api and I'm currently woking on plugin update

Can’t wait for it! When are you going to Release the plugin? :)

**Comment by Toxblh** [comment]
Hey, I recent receive the hum and wrote PR in python-miio
Maybe it will be helpful for you https://github.com/rytilahti/python-miio/pull/772

**Comment by malmentm** [comment]
Will it work with this? https://www.gearbest.com/humidifiers/pp_3004284366720564.html

**Comment by russtone** [comment]
Both models `deerma.humidifier.mjjsq` and `zhimi.humidifier.ca4` are supported by plugin, so I am closing this.
