### ISSUE TITLE
Target humidity is missing?

### ISSUE THREAD

**Issue by mrdc** [russtone/homebridge-mi-humidifier#18]
Hello,

I'm wondering if it's correct bahaviour or not: I can set the target humidity only via Mi Home app, not via Homekit - I see 3 positions for fan speed:
![image](https://user-images.githubusercontent.com/16876990/70042423-e30e4c00-15cf-11ea-868f-7596a556623f.png)
 and in settings I have a fan speed slider:
![image](https://user-images.githubusercontent.com/16876990/70042462-f3bec200-15cf-11ea-993d-2e162084d6ba.png)

**Comment by russtone** [comment]
Hey @mrdc,

Yes, it's ok. Home app doesn't display target humidity. Some other apps like Elgato Eve or Home+ can display it.

**Comment by mrdc** [comment]
Actually Homekit shows the target humidity level. What I mean is that there is no option to set the target humidity level via Homekit.
![image](https://user-images.githubusercontent.com/16876990/70044331-3766fb00-15d3-11ea-829d-e32103fde44c.png)

**Comment by russtone** [comment]
Yes, this is limitation of Apple's Home App

**Comment by leoneleone** [comment]
@mrdc 
I believe you can set Target Humidity via Siri Voice Commands, but cannot currently do so via the native Home.app 
If you want to set that as part of an automation, or just prefer using an app to change Target Humidity, use Eve.app or another capable 3rd Party app. 

Please let me know if setting Target Humidity via Siri Voice Command works for you.

**Comment by mrdc** [comment]
@leoneleone Thanks! Siri works fine for setting Target Humidity. Also I can do it manually in Eve app.
