### ISSUE TITLE
Issue with Xiaomi Mijia SCK0A45 Intelligent Sterilization Humidifier

### ISSUE THREAD

**Issue by MookieFumi** [russtone/homebridge-mi-humidifier#34]
Hi guys!
I'm trying to add my **Xiaomi Mijia SCK0A45 Intelligent Sterilization Humidifier** and i'm getting exceptions....

Do you know if this model is compatible with your plugin?

![Product image](https://imgaz3.staticbg.com/thumb/large/oaupload/ser1/banggood/images/A4/56/5e38b727-9f21-4d5a-9ee8-1738741486ec.jpg)

**Comment by ChristianPorsche** [comment]
I am curious too

**Comment by russtone** [comment]
Hey @MookieFumi,

Could you please send logs with exceptions?

**Comment by MookieFumi** [comment]
Yes, of course. Let me know if I can help but I've just checked with the "Mi Home" version 5.4.54 on Android to get the Ip and the token.

```json
{
    "did": "236569073",
    "token": "ee2d9d0cdb04f40e958d960794aee954",
    "name": "Humidificador",
    "pid": "0",
    "localip": "192.168.1.40",
    "ssid": "OrgullososDeNoSerComoVosotros",
    "parent_id": "",
    "parent_model": "",
    "show_mode": 1,
    "model": "deerma.humidifier.mjjsq",
    "adminFlag": 1,
    "shareFlag": 0,
    "permitLevel": 16,
    "isOnline": true,
    "desc": "",
    "prop": {
        "Humidifier_Gear": "4",
        "Humidity_Value": "63"
    }
}
```

And now it's working properly so maybe the issue was a non ok Ip or Token so my main doubt is when the ip or the token has changed? Everytime I unplug the humidifier?

I have another doubt about the humidifier screen in Home. Which is the main difference between the blue power button and the green one?

![image](https://user-images.githubusercontent.com/4056557/87850515-30d28d00-c8f1-11ea-9eb9-c59336085d17.png)

**Comment by yceballost** [comment]
i am having problems too.

```
getChildLock Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}

 getChildLock Error: busy.
    at Object.reject (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}

```

**Comment by russtone** [comment]
Model `deerma.humidifier.jsq1` is supported by the plugin, so I am closing this.
