### ISSUE TITLE
Homebridge error

### ISSUE THREAD

**Issue by stalkerj** [russtone/homebridge-mi-humidifier#36]
Fail to discover the device. Retry in 1 minute Error: Could not connect to device, handshake timeout
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:427:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
 {
  code: 'timeout',
  device: null
}

What can be wrong? Token got from modified me homу, ip correct

**Comment by russtone** [comment]
Looks like network connection problem. You can check that token and IP are correct by running:

```
npm install -g miio
miio tokens update <deviceIP> --token <deviceToken>
DEBUG=miio\*,thing\* miio inspect <deviceIP>
```

**Comment by stalkerj** [comment]
DEBUG=miio\*,thing\* miio inspect 10.0.1.6
 INFO  Attempting to inspect 10.0.1.6
  miio:network Grabbing reference to network +0ms
  miio:network Making network active, creating socket +1ms
  miio:packet -> <Buffer 21 31 00 20 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff> +0ms
  miio:network Network bound to port 52851 +7ms
  miio:packet <- <Buffer 21 31 00 20 00 00 00 00 05 e3 34 9e 00 00 25 72 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff> +96ms
  miio:packet <- <Buffer 21 31 00 20 00 00 00 00 05 e3 34 9e 00 00 25 72 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff> +0ms
  thing:miio:pending <- Handshake reply: <Buffer ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff> +0ms
  thing:miio:98776222 Identifier of device updated +0ms
  thing:miio:98776222 Loading token from storage, device hides token and no token set via options +1ms
  miio:tokens Loading token storage from /Users/evgeniybobylev/Library/Application Support/miio/tokens.json +0ms
  miio:tokens Loading tokens +1ms
  thing:miio:98776222 Using manual token: 24004015eb54d2a86e0ce5c26bc31173 +3ms
  thing:miio:98776222 -> (5) {"method":"miIO.info","params":[],"id":1} +2ms
  miio:packet -> <Buffer 21 31 00 50 00 00 00 00 05 e3 34 9e 00 00 25 72 60 ca 3e 79 f3 8b 9a 53 b7 c1 cc ef ce e6 4b cd> +8ms
  miio:packet <- <Buffer 21 31 02 00 00 00 00 00 05 e3 34 9e 00 00 25 72 9c 16 c9 d8 3c 4a ca e0 4d 9c 36 58 6a de 47 f8> +211ms
  miio:packet <- <Buffer 21 31 02 00 00 00 00 00 05 e3 34 9e 00 00 25 72 9c 16 c9 d8 3c 4a ca e0 4d 9c 36 58 6a de 47 f8> +1ms
  thing:miio:98776222 <- Message: `{"id":1,"result":{"life":9586,"uid":1576105710,"model":"zhimi.humidifier.ca1","token":"24004015eb54d2a86e0ce5c26bc31173","ipflag":1,"fw_ver":"2.0.5","mcu_fw_ver":"1033","miio_ver":"0.0.8","hw_ver":"MTK7697","mmfree":77776,"mac":"7C:49:EB:AF:22:80","wifi_fw_ver":"20200703173559","ap":{"ssid":"Home Sweet Home","bssid":"52:FF:20:5F:FB:87","rssi":-49,"primary":8},"netif":{"localIp":"10.0.1.6","mask":"255.255.255.0","gw":"10.0.1.1"},"config_type":"app"},"exe_time":62}` +214ms
  miio:network Grabbing reference to network +314ms
  miio:network Releasing reference to network +3ms
  thing:miio:98776222 -> (5) {"method":"miIO.info","params":[],"id":2} +7ms
  miio:packet -> <Buffer 21 31 00 50 00 00 00 00 05 e3 34 9e 00 00 25 72 ea 1e cc 42 c2 14 f3 2a a2 db 3a 0d 4e 8b 2f bc> +8ms
  miio:packet <- <Buffer 21 31 02 00 00 00 00 00 05 e3 34 9e 00 00 25 72 7e 03 ed 07 98 cd c2 3a 5d e6 86 05 af 3b 41 f1> +172ms
  miio:packet <- <Buffer 21 31 02 00 00 00 00 00 05 e3 34 9e 00 00 25 72 7e 03 ed 07 98 cd c2 3a 5d e6 86 05 af 3b 41 f1> +0ms
  thing:miio:98776222 <- Message: `{"id":2,"result":{"life":9586,"uid":1576105710,"model":"zhimi.humidifier.ca1","token":"24004015eb54d2a86e0ce5c26bc31173","ipflag":1,"fw_ver":"2.0.5","mcu_fw_ver":"1033","miio_ver":"0.0.8","hw_ver":"MTK7697","mmfree":77776,"mac":"7C:49:EB:AF:22:80","wifi_fw_ver":"20200703173559","ap":{"ssid":"Home Sweet Home","bssid":"52:FF:20:5F:FB:87","rssi":-48,"primary":8},"netif":{"localIp":"10.0.1.6","mask":"255.255.255.0","gw":"10.0.1.1"},"config_type":"app"},"exe_time":64}` +173ms

Device ID: 98776222
Model info: zhimi.humidifier.ca1
Address: 10.0.1.6
Token: 24004015eb54d2a86e0ce5c26bc31173 via stored token
Support: At least generic

Type info: miio
Capabilities: 

Firmware version: 2.0.5
Hardware version: MTK7697
MCU firmware version: 1033

WiFi: Home Sweet Home (52:FF:20:5F:FB:87) RSSI: -48
WiFi firmware version: 20200703173559

Remote access (Mi Home App): Maybe

**Comment by russtone** [comment]
Did you run these commands from the device running homebridge?

**Comment by stalkerj** [comment]
Я делал это с Мака который в той же сети.
Вот что происходит когда делаю из бриджа

/homebridge # miio tokens update 10.0.1.6 --token 24004015eb54d2a86e0ce5c26bc311
73
 INFO  Updating token for 10.0.1.6
 WARNING  Could not find device

**Comment by stalkerj** [comment]
/homebridge # miio tokens update 10.0.1.6 --token 24004015eb54d2a86e0ce5c26bc311
73
 INFO  Updating token for 10.0.1.6
 WARNING  Could not find device
/homebridge # miio discover sync
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 181930141
Model info: Unknown
Address: 10.0.1.220
Token: ???
Support: Unknown

Device ID: 98776222
Model info: Unknown
Address: 10.0.1.6
Token: ???
Support: Unknown

^Z[1]+  Stopped                    miio discover sync
/homebridge # miio tokens update 10.0.1.6 --token 24004015eb54d2a86e0ce5c26bc311
73
 INFO  Updating token for 10.0.1.6
 WARNING  Could not find device
/homebridge # DEBUG=miio\*,thing\* miio inspect 10.0.1.6
 INFO  Attempting to inspect 10.0.1.6
  miio:network Grabbing reference to network +0ms
  miio:network Making network active, creating socket +1ms
  miio:packet -> <Buffer 21 31 00 20 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff> +0ms
  miio:network Network bound to port 45878 +10ms
  miio:network Releasing reference to network +2s
  miio:network Network no longer active, destroying socket +0ms
 WARNING  Could not find device
/homebridge #

**Comment by russtone** [comment]
Честно говоря, не могу сказать, в чем проблема. Так как с мака работает, а с homebridge - нет, то проблема скорее всего в настройках сети на homebridge. Может быть что-то такое: https://github.com/aholstenson/miio/issues/92#issuecomment-370274558

**Comment by ursusHU** [comment]
I have the same issue. It is occuring when the Humidifier is not connected to the outlet. After longer period of time the discovery doesn't work anymore (ofc the Humidifier is powered on again). However the unit can be accessed via MiHome app. Restarting Homebridge solves the problem.
