### ISSUE TITLE
Adapter doesn't supported model:  v1

### ISSUE THREAD

**Issue by Phoendor** [russtone/homebridge-mi-humidifier#37]
Hi!

Homebridge started putting line "Adapter doesn't supported model:  v1" in log, no other lines concerning Humidifier. Also it cannot be controlled on the "Accessories" tab of the Homebridge.

Config:
        {
            "name": "Увлажнитель",
            "ip": "192.168.1.210",
            "token": "9936a73b0107e0cab998440ae88c57",
            "model": "v1",
            "showMuteSwitch": false,
            "nameMuteSwitch": "Mute humidifier",
            "showTemperature": true,
            "nameTemperature": "Увлажнитель Термометр",
            "showHumidity": true,
            "nameHumidity": "Увлажнитель Гигрометр",
            "accessory": "MiHumidifier"
        },

**Comment by mrdc** [comment]
Remove `"model": "v1",` from your config. It fixes the issues.

**Comment by Phoendor** [comment]
Removed, but now it's another error
Adapter doesn't supported model:  undefined

**Comment by paqpaqpaq** [comment]
same here

**Comment by russtone** [comment]
There shouldn't be such problem in the new version, so I am closing this for now.
