### ISSUE TITLE
Support disabling/dimming LED

### ISSUE THREAD

**Issue by bedrin** [russtone/homebridge-mi-humidifier#39]
At least some humidifiers support dimming and even turning off the LED.
```
set_led_b '["0"]'
get_prop '["led_b"]'
```

Properties:
0 - on
1 - dimmed
2 - off

**Comment by russtone** [comment]
Hey @bedrin,
This is implemented in version 2. To enable this feature you need to add the following lines to device config:

```
"ledBulb": {
  "enabled": true
},
```

The config format is changed in the new version, please check readme for more details.
