### ISSUE TITLE
After Updating from v.1.3.0 to v.1.4.0

### ISSUE THREAD

**Issue by Hyoengju-Johannes-Lee** [russtone/homebridge-mi-humidifier#41]
**Error Message**
Error: The requested accessory 'MiHumidifier' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge/src/server.ts:347:37)
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Config**
...
"accessories": [
        {
            "name": "Humidifier",
            "ip": "192.168.1.110",
            "token": "7901cd9ea76ae5554376ea636cb5642c",
            "showMuteSwitch": true,
            "nameMuteSwitch": "Mute humidifier",
            "showTemperature": true,
            "nameTemperature": "Temperature",
            "showHumidity": true,
            "nameHumidity": "Humidity",
            "accessory": "MiHumidifier"
        }
    ],
...

I am using homebridge under such environment
Raspberry Pi 4 Model B Rev 1.1
Raspbian GNU/Linux 10 (buster)
node v10.21.0
hb-service version is v4.31.0

And I set the humidifier deerma mjjsq version.

**Comment by heshuimu** [comment]
I saw this issue, too. The plugin has changed where it looks for configuration and it did not do migration(!!!!!). 

The solution was to go into config file, cut the old config so that homebridge can boot (else, boot loop), use the homebridge UI to add back the devices referencing the old config. 

Here's the new config format in case anyone needs reference. 
```json
{
    "platforms": [
        {
            "devices": [
                {
                    "disabled": false,
                    "name": "Humidifier",
                    "address": "...",
                    "token": "...",
                    "model": "zhimi.humidifier.cb1",
                    "updateInterval": 10,
                    "temperatureSensor": {
                        "enabled": false,
                        "name": "Temperature"
                    },
                    "humiditySensor": {
                        "enabled": true,
                        "name": "Humidity"
                    },
                    "ledBulb": {
                        "enabled": false,
                        "name": "Led"
                    },
                    "buzzerSwitch": {
                        "enabled": false,
                        "name": "Buzzer"
                    }
                }
            ],
            "platform": "MiHumidifier"
        }
    ]
}
```

**Comment by russtone** [comment]
There shouldn't be such problem in the new version, so I am closing this for now.
