### ISSUE TITLE
add support for shuii.humidifier.jsq001

### ISSUE THREAD

**Issue by vhardono** [russtone/homebridge-mi-humidifier#43]
hi, would you be able to add support for **shuii.humidifier.jsq001** ?
I found this supported in Home Assistant but not in Homebridge --> [https://github.com/rytilahti/python-miio/issues/642](url)

Thank you

**Comment by russtone** [comment]
Hey! I've just published v2 version, which should support this version.
Could you please test it?
It is in beta now, so to install it you need to run `npm install -g homebridge-mi-humidifier@latest`.
Also, configuration is changed, please check the example here https://www.npmjs.com/package/homebridge-mi-humidifier/v/2.0.0-beta.0

**Comment by russtone** [comment]
Model `shuii.humidifier.jsq001` is supported by the new version of the plugin, so I am closing this. If you find any problems, please create a new issue.
