### ISSUE TITLE
Humidifier (ca4-Modell) does not stop ventilating once the set target-humidity has been reached

### ISSUE THREAD

**Issue by bubffm** [russtone/homebridge-mi-humidifier#44]
There appears to be an issue with controlling the SmartMi humidifier using target humidity. I would have expected that the ventilator switches off once the target humidity has been reached, and, consequently, that it will switch on again once the actual humidity falls below the set target humidity.

This does not appear to be the case. The humidifier keeps ventilating / rotating even after reaching the target.

Resetting the humidifier and reconnecting with new token does not solve the issue.

Is this a known problem?   Thanks for having a look into it.

![IMG_0144](https://user-images.githubusercontent.com/49747999/101920948-b884a500-3bcc-11eb-8d36-58e563389d7f.jpeg)

**Comment by DJay-X** [comment]
@russtone Same here. When reaching target Humidity, the Humidifier is still running. 
Actually it is running all the time. 😅
Would be great if the plugin could handle this better if possible. 
Also any news on this issue? https://github.com/russtone/homebridge-mi-humidifier/issues/26#issuecomment-731571671

Thank again for you work and sharing with the community.

**Comment by bubffm** [comment]
@russtone 
has this issue been picked up in 2.0.0.x beta?

As far as I can tell, the humidifier still keeps running after reaching target humidity.

**Comment by russtone** [comment]
I believe that `ca4` model have the special mode for this `auto`. This mode can be enabled by setting rotation speed to max value.
Could you try to set mode to auto and check if it helps?

**Comment by bubffm** [comment]
Thanks for the pointer.  

I can see on the screen, that putting rotation to max (4%) enables the auto mode.  
When the actual humidity is higher than the target humidity the wheel stops, but the ventilator keeps running.
If I increase target humidity to a higher value, that the wheel starts rotating again.

So it "sort-of-works" - but not really. I would have expected that not only the wheel stops but also the ventilator.  No point in wasting ventilation energy is the wheel is not spinning to add water for dispersion.....

Is this expected behavior?

What I also noticed: The "Status" is not being updated to "Auto" when I switch to Auto-Ode.  It stay on "Humidifier".

**Comment by russtone** [comment]
The behaviour you've described is not controlled by this plugin, its is controlled by humidifier firmware. This plugin only provides ability to control parameters provided by humidifier firmware using homekit interface.
The "Status" field is not related to "auto" mode of rotation speed, it is related to humidifier/dehumidifier state. Xiaomi humidifiers don't support dehumidifying, so this switch do nothing.

**Comment by bubffm** [comment]
Thanks again. In that case all works as expected. I'll probably not use the build-in auto-mode and work around this with some homekit-automations switching the humidifiers on or off based on certain parameters.
