### ISSUE TITLE
Home.app frequently shows "not responding" and Siri cannot control humidifer at first try

### ISSUE THREAD

**Issue by ZEMUSHKA** [russtone/homebridge-mi-humidifier#45]
Thanks for the plugin, @russtone!

I've found that two requests that you make to overcome sleep after idle issue doesn't work that well for me.
I've decided to do a constant polling of my humidifer (for any characteristic really) to prevent it from going idle.
Now I don't see any "not responding" issues for 2 days straight.

These are the changes I've made: https://github.com/russtone/homebridge-mi-humidifier/compare/master...ZEMUSHKA:master, maybe it will help someone.

I understand that it will eat more power, but I assume it's negligible comparing with that huge fan we need to power.
Also, I haven't seen a single retry in 2 days, look like they've all happened because of 2 simultaneous requests and race that ends up with "busy" error.

**Comment by ZEMUSHKA** [comment]
This is my log file for today, if anyone cares:
[homebridge.log.txt](https://github.com/russtone/homebridge-mi-humidifier/files/5685413/homebridge.log.txt)

**Comment by bubffm** [comment]
As I am having the very same issues, how do I apply those changes to my setup?  Or does this need an update of the plugin itself?

**Comment by russtone** [comment]
Hey! I've just published v2 version, which implements polling as @ZEMUSHKA suggested and fixes some other issues.
Could you please test it?
It is in beta now, so to install it you need to run `npm install -g homebridge-mi-humidifier@latest`.
Also, configuration is changed, please check the example here https://www.npmjs.com/package/homebridge-mi-humidifier/v/2.0.0-beta.0

**Comment by mac8005** [comment]
> Hey! I've just published v2 version, which implements polling as @ZEMUSHKA suggested and fixes some other issues.
> Could you please test it?
> It is in beta now, so to install it you need to run `npm install -g homebridge-mi-humidifier@latest`.
> Also, configuration is changed, please check the example here https://www.npmjs.com/package/homebridge-mi-humidifier/v/2.0.0-beta.0

Great! Could you also add support for deerma.humidifier.jsq ?
thanks

**Comment by bubffm** [comment]
Installed version 2 beta.  It aborts with msg "accessory not registered by any plugin"...... 

Homebridge never starts.....

**Comment by bubffm** [comment]
OK, installed for my 3 ca4 humidifiers.  I will monitor how it keeps track.   

I got the following error on LED:

`Fail to set property 'led_brightness'. Error: Invalid result: {"did":"led_brightness","siid":5,"piid":1,"code":-4004}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/src/devices/protocols/protocol.ts:119:13)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/src/devices/humidifier.ts:194:7)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/src/devices/humidifier.ts:137:20)`

Minor but maybe you know what this means?

Question: The "30" in the updateInterval: Is that seconds?

Thanks for the quick response to this nagging issue.

**Comment by russtone** [comment]
@bubffm, yes, 30 in "updateInterval" means 30 seconds

**Comment by russtone** [comment]
There shouldn't be such problem in the new version, so I am closing this for now.
