### ISSUE TITLE
HomeKit Tile Always shows “Rising to x”

### ISSUE THREAD

**Issue by ursusHU** [russtone/homebridge-mi-humidifier#55]
When off I think the tile should show off instead of the text rising to x
![C5ED06FE-069F-45DE-8B2E-4179840F0561](https://user-images.githubusercontent.com/61931127/103158362-292ae480-47bd-11eb-8173-bfa3fdb98c5c.jpeg)

**Comment by russtone** [comment]
This should be fixed in the latest version. Tile will be updated on next poll so it might take some time

**Comment by ursusHU** [comment]
Works

**Comment by bubffm** [comment]
Not for me.  Installed Beta 8 four hours or so ago and still says in Home App "Auf 44% erhöhen". (rasing to 44%)....

**Comment by russtone** [comment]
The devices on your screenshot are enabled.  Is there still message "Rising to ..." if you disable them?
This issue was related to message "Rising to ..." when humidifier is disabled.

**Comment by bubffm** [comment]
They are enabled.  But it always says raising to 44% when they are set to 52% or 54% in Eve App...
