### ISSUE TITLE
Graceful error handling for inactive / unplugged devices

### ISSUE THREAD

**Issue by bubffm** [russtone/homebridge-mi-humidifier#56]
As the humidifier is a "seasonal" product which I will put in the cellar at the end of the heating season (Late February / Mid March over here), I wonder whether it might be possible to give a "smart" message that the device is not plugged in rather than a full throttled error that can take the homebridge down.

Alternative would be, that I'd have to take the entries for my humidifiers out of config, save them somewhere else, and put them back in again for the next heating season, which isnt very comfortable.

Is this something that might be possible to consider, maybe by adding a config item "smart error": true/false - or similar?

Many thanks

**Comment by russtone** [comment]
Hey @bubffm,
The error handling changed in the latest version, so they should look nicer now.
Maybe it will be better to add flag "enabled" (true/false) to device config to temporary disable it?
By default it will be equal to `true`.

**Comment by bubffm** [comment]
>>. Maybe it will be better to add flag "enabled" (true/false) to device config to temporary disable it?

That sounds like a good way of handling it.

**Comment by russtone** [comment]
Hey @bubffm,
I've added new option `"disabled": true/false` (`false` by default) to device config in the latest version.
This should fix the issue.

**Comment by bubffm** [comment]
hey @russtone,

thanks thats great.  Could you just add that to the sample config for documentation purposes.  Many thanks

**Comment by russtone** [comment]
Added description to README.md
