### ISSUE TITLE
Does this plugin support Xiaomi Humidifier 4th?

### ISSUE THREAD

**Issue by manggoo71** [russtone/homebridge-mi-humidifier#59]
<img width="353" alt="스크린샷 2021-01-20 오전 12 22 31" src="https://user-images.githubusercontent.com/58352490/105054882-d4c20e80-5ab5-11eb-9b5a-0f9155d8a9d3.png">

I installed the same plug-in on the Hoobs platform. Does Xiaomi also support 4th generation humidifier? What is the model name?

"zhimi.humidifier.v1", "zhimi.humidifier.ca1", "zhimi.humidifier.cb1", "zhimi.humidifier.ca4", "deerma.humidifier.mjjsq", "shuii.humidifier.jsq001". Default is "zhimi.humidifier.v1"

**Comment by russtone** [comment]
Hey @manggoo71,

This looks like `"deerma.humidifier.mjjsq"`

**Comment by russtone** [comment]
I've updated README.md and added better description of supported devices.
