### ISSUE TITLE
Please add water level to master

### ISSUE THREAD

**Issue by netRunner0** [russtone/homebridge-mi-humidifier#6]
https://github.com/leoneleone/homebridge-mi-humidifier

**Comment by russtone** [comment]
It is already in the master: https://github.com/leoneleone/homebridge-mi-humidifier/blob/c100f2a537a9464ae3ee01e06cbd334b41e01b6e/index.js#L65. You just need to set `model` parameter in your config to `ca1`.

**Comment by russtone** [comment]
The first version of Xiaomi Humidifier (`zhimi.humidifier.v1`) doesn't have support of water level.

**Comment by claulsc** [comment]
Is it possible to add support for water level for zhimi.humidifier.ca4?

**Comment by czekal** [comment]
> Is it possible to add support for water level for zhimi.humidifier.ca4?

I wont this option too :(

**Comment by russtone** [comment]
> Is it possible to add support for water level for zhimi.humidifier.ca4?

Water level for ca4 is supported. If it is not working properly, please create a new issue and describe a problem.

**Comment by czekal** [comment]
> Is it possible to add support for water level for zhimi.humidifier.ca4?

I installed component 6.1 version and naw is warking.
