### ISSUE TITLE
When importing to Home Assistant Integration, there is an error.

### ISSUE THREAD

**Issue by Hyoengju-Johannes-Lee** [russtone/homebridge-mi-humidifier#65]
I have two humidifiers, which is both configured with this plugin.!

<img width="1095" alt="스크린샷 2021-01-26 23 05 57" src="https://user-images.githubusercontent.com/62842483/105906156-fed27e00-602b-11eb-9700-3bcff2463ac3.png">

There is no problem in configuration, I just set using the "settings" in the plugin menu. 

    "platforms": [
        {
            "devices": [
                {
                    "name": "Bedroom Humidifier",
                    "address": "192.168.1.129",
                     ...
                    }, ...
                },
                {
                    "name": "Living Room Humidifier",
                    "address": "192.168.1.128",
                      ...
                }
            ],
            "platform": "MiHumidifier"
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]

From the screenshot below, I guess that is because of the Name "Humidifier" or "Serial Number" which is in both of the humidifiers.
The screenshot is from one of the humidifiers in "Accessories" menu.

<img width="794" alt="스크린샷 2021-01-26 23 21 00" src="https://user-images.githubusercontent.com/62842483/105907078-34c43200-602d-11eb-8519-1800e1a6182a.png">

I am always grateful for your contributions.!

**Comment by russtone** [comment]
Hey @Hyoengju-Johannes-Lee

Which version of the plugin do you use? The problem with duplicate serial numbers (#58) should be fixed since version 2.1.0

**Comment by Hyoengju-Johannes-Lee** [comment]
Ah, sorry for my carelessness.! I checked titles of other issues before writing, but since I was not sure it was because of serial numbers, I didn't know that there was a same issue.!
Thanks.! Let me just update to a new version.!
