### ISSUE TITLE
Не регулируется скорость вращения. Не переходит в режим осушителя.

### ISSUE THREAD

**Issue by delobanov** [russtone/homebridge-mi-humidifier#70]
Здравствуйте!
Почему-то не доступны никакие регулировки кроме целевого уровня влажности в приложении Дом. При выключении увлажнителя на плитке все равно отображается целевая влажность, вместо выключения. 
![photo_2021-02-12_12-18-46](https://user-images.githubusercontent.com/37274413/107750033-7db5ff00-6d2c-11eb-95c5-e8f5fcf15b51.jpg)
![photo_2021-02-12_12-20-54](https://user-images.githubusercontent.com/37274413/107750239-cd94c600-6d2c-11eb-80ce-3469f182992c.jpg)

Конфиг:
`{
            "devices": [
                {
                    "disabled": false,
                    "name": "Увлажнитель",
                    "address": "172.17.0.181",
                    "token": "2713b7a7cadbcc4afc91601b443886a3",
                    "model": "zhimi.humidifier.cb1",
                    "updateInterval": 1,
                    "temperatureSensor": {
                        "enabled": true,
                        "name": "Температура воздуха"
                    },
                    "humiditySensor": {
                        "enabled": true,
                        "name": "Влажность воздуха"
                    },
                    "ledBulb": {
                        "enabled": false,
                        "name": "Led"
                    },
                    "buzzerSwitch": {
                        "enabled": false,
                        "name": "Buzzer"
                    }
                }
            ],
            "platform": "MiHumidifier"
        }`

**Comment by mrskycriper** [comment]
Остальные настройки прячутся в самом аксессуаре, у вас наверняка что-то еще с ним сгруппировано на 1 плитку, потому снизу и нет настроек. Нажмите на шестеренку > аксессуары > лонг тап на сущность увлажнителя и увидите его настройки.

**Comment by russtone** [comment]
Все верно, все регулировки доступны по клику на шестеренку в правом нижнем углу.

<img src="https://user-images.githubusercontent.com/3396041/107943904-6716de80-6f9e-11eb-90a0-cf649ab2307d.PNG" width="400" />

<img src="https://user-images.githubusercontent.com/3396041/107944047-a0e7e500-6f9e-11eb-8689-a00217448e10.PNG" width="400" />

Что касается плитки, то она по умолчанию обновляется раз в 30 секунд, поэтому просто нужно немного подождать.

**Comment by delobanov** [comment]
Действительно нашел регулировки в плитке увлажнителя внутри составного устройства, в котором еще гигрометр и термометр. Раньше интерфейс был гораздо удобнее, можно было скорость выбирать там, где сейчас целевая влажность. Кроме того, сейчас в сценариях не получается скорость менять, потому что устройство нельзя на отдельные плитки разделить, нет соответствующей кнопки. Да и разделив его, все равно не думаю, что получится.

**Comment by russtone** [comment]
Разделить на плитки можно там же, по клику на шестеренку:

<img src="https://user-images.githubusercontent.com/3396041/107946583-48b2e200-6fa2-11eb-978b-8f7192e01f93.jpeg" width=400 />

Также гигрометр и термометр можно отключить через конфигурацию плагина.

Изменение скорости доступно из сцен и атоматизаций:

https://user-images.githubusercontent.com/3396041/107946979-d098ec00-6fa2-11eb-8cb6-6e4580220656.MP4

Плагин не управляет интерфейсом в Home.app, он только реализует получение/установку всех необходимых параметров для устройства класса [Humidifier Dehumidifier](https://developers.homebridge.io/#/service/HumidifierDehumidifier). То, как он отображается в приложении, зависит только от самого приложения, возможно в более ранних версиях iOS он мог отображаться по-другому.

**Comment by delobanov** [comment]
Я понимаю, что плагин не управляет интерфейсом. Вопрос к Apple) 
А вот разделения на плитки у меня все же нет.
![photo_2021-02-15_16-27-00](https://user-images.githubusercontent.com/37274413/107952434-ce3a9000-6faa-11eb-8841-a35579adf494.jpg)
![photo_2021-02-15_16-27-03](https://user-images.githubusercontent.com/37274413/107952437-ced32680-6faa-11eb-80fd-b29c78844f62.jpg)

**Comment by russtone** [comment]
Возможно это связано с кешом homebridge, попробуйте добавить в конфиг `"disabled": true`, дождаться пока увлажнитель пропадет из Home.app, а потом вернуть `"disabled": false`

**Comment by russtone** [comment]
Добавил в новом релизе опцию `disableTargetHumidity`, которая отключает возможность контролировать целевую влажность, но при этом на основном экране устройства появляется возможность менять скорость:

<img src="https://user-images.githubusercontent.com/3396041/108709884-5e855180-7524-11eb-9a98-cd39d3717428.jpeg" width=400 />
