### ISSUE TITLE
Target humidity doesn’t do anything

### ISSUE THREAD

**Issue by mrskycriper** [russtone/homebridge-mi-humidifier#71]
Target humidity slider in HomeKit doesn’t do anything, even if i set it to 0% humidifier will still work 
![274793C5-E306-4276-956E-C1882AD524E8](https://user-images.githubusercontent.com/32013287/107942367-32098c80-6f9c-11eb-8a92-f054f37b14ef.png)

**Comment by russtone** [comment]
What is you humidifier model? On some humidifier models there is a special mode for target humidity, which can be enabled by setting fan speed to max value. More on this #44

**Comment by mrskycriper** [comment]
I have cb1 model. I guess everything that was said about ca4 is also true for my model

**Comment by russtone** [comment]
Yes, your model also has special "auto" mode. Maybe it will be better to automatically change mode to auto when target humidity is changed. What do you think?

**Comment by mrskycriper** [comment]
That is a good idea

**Comment by russtone** [comment]
Ok, I'll add special option in config for this behaviour in new release.

**Comment by russtone** [comment]
Hey @mrskycriper,

I've just published new release 2.3.0, now you can set `autoSwitchToHumidityMode` in config to enable automatic switching to "auto" mode when target humidity is changed. For more details see README.md
