### ISSUE TITLE
Problems with latest update v2.3.0 under homebridge 1.3.0 / 1.3.1

### ISSUE THREAD

**Issue by bubffm** [russtone/homebridge-mi-humidifier#77]
Somehow, I have accidentally closed my last issue and dont know how to reopen, so here we go again:

Actually there is an issue somehow with the latest update on the CA4. Automations no longer switch the humidifiers on. Switching them on manually, puts them on but leaves the switch in „off“ position, so no surprise the automations fail.....
Here the Error I get:

[MiHumidifier] [192.168.2.16] Fail to set device property "mode". Error: Invalid result: {"did":"mode","siid":2,"piid":5,"code":-4002}

I have :
`"autoSwitchhToHumidityMode": false,
"disableTargetHumidity": true,`

**Comment by bubffm** [comment]
Deleting
"autoSwitchhToHumidityMode": false, "disableTargetHumidity": true,
from config does unfortunatly not change anything. Plugin is still throwing error messages....

**Comment by bubffm** [comment]
Tried to move back to V2.2.3. but Npm tells me it's not in the registry....

**Comment by russtone** [comment]
> Switching them on manually, puts them on but leaves the switch in „off“ position, so no surprise the automations fail.....

State of device in the app is updated every 30 seconds, so if you turn humidifier "on" manually you need to wait for a bit for the status to change

> Tried to move back to V2.2.3. but Npm tells me it's not in the registry....

I haven't removed any old versions, they all must be available https://www.npmjs.com/package/homebridge-mi-humidifier.
Try `npm install homebridge-mi-humidifier@2.2.3`

**Comment by russtone** [comment]
Do you have this errors only when you use automations? Are there any errors when you change fan speed without automation?

**Comment by bubffm** [comment]
I get these errors only in the automations.  EVE is giving me a red exclamation mark and is just not executing it. The log throws that error that I posted above.

**Comment by bubffm** [comment]
> Try npm install homebridge-mi-humidifier@2.2.3

Did that. It ran thru, I rebooted homebridge, but the UI X interface still tells me I'm on 2.3.0 and it still "behaves" like 2.3.0

weird....

**Comment by bubffm** [comment]
[24/02/2021, 18:44:13] Loaded 3 cached accessories from cachedAccessories.
[Luftbefeuchter Schlafzimmer@@Identify] Characteristic not in required or optional characteristic section for service Service. Adding anyway.
[Luftbefeuchter Esszimmer@@Identify] Characteristic not in required or optional characteristic section for service Service. Adding anyway.
[Luftbefeuchter Klavier@@Identify] Characteristic not in required or optional characteristic section for service Service. Adding anyway.

**Comment by bubffm** [comment]
I believe I found the issue:  For some reason the cache must have been "corrupted". I set disabled to "true", reboot,  then disabled "false", another reboot.   Re-added the devices to the automations.

All seems to work again.  I'll monitor for a while. If confirmed, will close the issue.

**Comment by russtone** [comment]
Characteristic warnings should be fixed in the latest release 2.3.1. Do you still have problems with automations?

**Comment by bubffm** [comment]
No, automations are fine 👍
