### ISSUE TITLE
Compatibility to Xiaomi Evaporative Humidifier

### ISSUE THREAD

**Issue by Phoenix-DH** [russtone/homebridge-mi-humidifier#9]
Hey,

is this plugin compatible to this one:
https://www.aliexpress.com/item/2018-Original-Smartmi-Xiaomi-Evaporative-Humidifier-2-for-your-home-Air-dampener-Aroma-diffuser-essential-oil/32854744155.html?spm=a2g0s.8937460.0.0.574e2e0eaOufQZ

Do I need any bridge for that?

**Comment by russtone** [comment]
This plugin uses [miio](https://github.com/aholstenson/miio) library to control Xiaomi devices. So, if miio supports this device this plugin also does.
It is known that it works with SmartMi Germocidal UV Humidifier (zhimi.humidifier.v1) and SmartMi Evaporative Humidifier (zhimi.humidifier.ca1).

**Comment by russtone** [comment]
It seems that miio doesn't support SmartMi Evaporative Humidifier (zhimi.humidifier.ca1), but there is a workaround to make it work: https://github.com/russtone/homebridge-mi-humidifier/issues/5#issuecomment-453771970
